steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp:latest', '-t', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID', '.']
  id: 'build-image-myapp'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-myapp']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'myawesomeapp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  id: 'deploy-to-cloud-run'
  waitFor: [push-image-to-container-registry']
   
images:
- 'gcr.io/$PROJECT_ID/myapp:latest'

- 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA'























- 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID'
